hikrobot_camera:
  ros__parameters:
    image_topic: "/image_raw"

    # Hikrobot camera controls
    exposure_time: 5000.0   # us
    gain: 10.0
    frame_rate: 60.0        # FPS

    # MV_CC_GetImageBuffer timeout
    grab_timeout: 1000      # ms
